# Generated by Django 5.2.1 on 2025-05-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_groupmembership_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='joining_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
