# Generated by Django 5.2.1 on 2025-05-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_group_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='joining_code',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
