# Generated by Django 5.2.1 on 2025-06-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
    ]
